# Generated by Django 5.2.8 on 2026-01-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="player_photos/"),
        ),
    ]
