# Generated by Django 5.2.8 on 2026-01-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_player_phone_number_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.CharField(choices=[('Def', 'Defender'), ('For', 'Forward'), ('Goal', 'Goalkeeper'), ('Mid', 'Midfielder')], max_length=4),
        ),
    ]
