# Generated by Django 5.2.8 on 2026-02-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_player_player_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionstatus',
            name='previous_bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auctionstatus',
            name='previous_bid_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_bids', to='auction.team'),
        ),
        migrations.AlterField(
            model_name='auctionstatus',
            name='current_bid_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bids', to='auction.team'),
        ),
    ]
