# Generated by Django 5.2.8 on 2026-02-25 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auctionstatus_previous_bid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='sold_to_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='auction.team'),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('team_capacity', models.PositiveIntegerField(default=0)),
                ('auction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.sportstype')),
            ],
        ),
    ]
