# Generated by Django 5.2.8 on 2026-02-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_sportstype_alter_player_sold_to_team_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(default='Auction', max_length=200),
        ),
    ]
