# Generated by Django 5.2.8 on 2026-02-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_alter_settings_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='auction_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='random_row',
            field=models.FloatField(default=0.0),
        ),
    ]
